name:  workflow_dispatch
on:
  workflow_dispatch:
    inputs:
      application_name:
        description: 'application name'
        required: true
        type: string
      run_validation:
        description: 'validation'
        required: true
        type: boolean
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "----Runtime variables---"
          echo "${{inputs.application_name}}"
          echo "${{inputs.run_validation}}"

      - run: |
          if ( "${{inputs.run_validation}}" = "true" ); then
            
             echo "validation_status == success" >> $GITHUB_OUTPUT

          else
             
             echo "validation_status == success" >> $GITHUB_OUTPUT

          fi

  summary:
    runs-on: ubuntu-latest
    needs: validate
    if: ${{needs.validate.outputs.validation_status == 'success'}}
    steps:
      - run: echo "completed"
